<?
project has moved to tech.yoka.com

exit;

/**
 * for counter 
 * 
 * by jimmy 2009.07.16
 *
 * usage:

ref to: c.test.php

 *
 */
$log_path="/var/php_log";
$log_version=1;
$flag_return=0;
$flag_user=0;

header("Cache-Control: no-cache, must-revalidate");
header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
//var_dump($_SERVER);
$refer=$_SERVER['HTTP_REFERER'];
$ip=$_SERVER['REMOTE_ADDR'];$ip_info=explode('.',$ip);
$raw=$_SERVER['QUERY_STRING'];
$screen_width=intval($_GET['sw']);
$screen_height=intval($_GET['sh']);
$client_width=intval($_GET['ww']);
$client_height=intval($_GET['wh']);
$is_top_window=intval($_GET['tp']);
$c_id=intval($_GET['c_id']); //channel id
$single_count=intval($_GET['sc']);     //single count
if(!get_magic_quotes_gpc())$brower=addslashes($_GET['ua']);
else $browser=$_GET['ua'];
if(!get_magic_quotes_gpc())$pre_refer=addslashes($_GET['rf']);
else $pre_refer=$_GET['rf'];

$timenow=time();
$now=date("Y-m-d H:i:s",$timenow);

if(!$_COOKIE['ct']){
  $expire=$timenow+3600*24*30*6;
  $cookie_tag=substr(md5($ip_info[0].'.'.$ip_info[1].'.'.$browser),0,24).rand(10000000,99999999); //32B
  setcookie('ct',$cookie_tag,$expire);
}else{
  $cookie_tag=$_COOKIE['ct'];
  $flag_return=1;
}
if($_COOKIE['uid']){  //............................ THIS IS NOT DO YET ! ............................
  $cookie_userid=$_COOKI['uid'];
  $flag_user=1;
}

/* channel prematch */
if(!$c_id){
 include('c.inc.php'); //regular config file, generated by counter_geninc.php
 $flag_match_reg=0;
if($debug)var_dump($reglist);
 foreach($reglist as $d_id=> $reginfo){
  $reg=$reginfo['reg'];if($reg=='')continue;
  if(preg_match('|'.$reg.'|is',$refer)){$flag_match_reg=1;if($reginfo['d_continue']!=1)break;}
 }
 if($flag_match_reg==0){
 $c_id=5;  //Other channel. Do not need write to channel log.
 }
}else $flag_match_reg=2; //channel defined from the page. ::Maybe cheating!::

$log_data=array('log_version'=>$log_version,
'c_id'=>$c_id,'flag_match_reg'=>$flag_match_reg,
'ip'=>$ip,
'refer'=>$refer,
'pre_refer'=>$pre_refer,
'cookie_tag'=>$cookie_tag,'flag_return'=>$flag_return,
'flag_user'=>$flag_user,'cookie_userid'=>$cookie_userid,
'screen_width'=>$screen_width,'screen_height'=>$screen_height,
'client_width'=>$client_width,'client_height'=>$client_height,
'is_top_window'=>$is_top_window,'single_count'=>$single_count);

// write to all pv's log
if(!$single_count){
$tmp_5m=date("H")."-".sprintf("%02d",floor(intval(date("m"))/5)*5)."_".substr($cookie_tag,0,1);
$tmp_filename=$log_path."/RAW/LOG_".date("Y-m-d")."/ALL/5m_".$tmp_5m.".log";
c_file_log($tmp_filename,$log_data);
}

// write to channel log
if($channel[c_5m]>0)$tmp_c5m="_".substr($cookie_tag,0,$channel[c_5m]);
else $tmp_c5m='';
$tmp_5m=date("H")."-".sprintf("%02d",floor(intval(date("m"))/5)*5).$tmp_c5m;
$tmp_filename=$log_path."/RAW/LOG_".date("Y-m-d")."/CHANNEL/5m_".$tmp_5m.".log";
c_file_log($tmp_filename,$log_data);

// write to signed user log
if($cookie_userid){
$tmp_5m=date("H")."-".sprintf("%02d",floor(intval(date("m"))/5)*5)."_".substr($cookie_tag,0,1);
$tmp_filename=$log_path."/RAW/LOG_".date("Y-m-d")."/USER/5m_".$tmp_5m.".log";
c_file_log($tmp_filename,$log_data);
}

/* --------------------- function ---------------------*/
function c_file_log($file_name,$log_data){
//echo "<hr>$file_name;<pre>";
//var_dump($log_data);
//echo "</pre>";
mkdirs($file_name);
file_put_contents($file_name,implode(' | ',$log_data));

}
function c_table_log($file_name,$log_data){

}
function mkdirs($pathStr,$mod="0755"){
    if(is_file($path) || is_dir($pathStr)) return true;
    $pieces = explode("/", $pathStr);
    $tmpdir = "";
    for($mm=1;$mm<(count($pieces)-1);$mm++){
        $tmpdir      .= "/".$pieces[$mm];
        if(!is_dir($tmpdir)){
            if (!mkdir($tmpdir,$mod)) return false;
        }
    }
    return true;
} 

?>
